<?php

// This file is automatically generated and modified by phpMyBackupPro v.2.2

$CONF['sql_user']="sar";
$CONF['sql_passwd']="td72da";
$CONF['sql_host']="localhost";
$CONF['sql_db']="";
$CONF['ftp_use']="0";
$CONF['allow_dir_backup']="0";
$CONF['email_use']="0";
$CONF['sitename']="sar";
$CONF['lang']="espanol";
$CONF['import_error']="1";
$CONF['no_login']="0";
$CONF['login']="0";
$CONF['dir_backup']="1";
$CONF['dir_rec']="1";
$CONF['email']="";
$CONF['ftp_pasv']="1";
$CONF['ftp_del']="1";
$CONF['ftp_server']="example.net";
$CONF['ftp_user']="";
$CONF['ftp_passwd']="";
$CONF['ftp_path']="example/";
$CONF['ftp_port']="21";
$CONF['date']="%Y/%m/%d %X";
$CONF['del_time']="30";
$CONF['del_number']="15";
$CONF['timelimit']="60";
$CONF['confirm']="1";
$CONF['stylesheet']="standard";

$PMBP_SYS_VAR['last_scheduled']="1492607895";
$PMBP_SYS_VAR['this_login']="2012/09/13 18:39:03 (IP: 192.168.1.34)";
$PMBP_SYS_VAR['last_login']="2012/09/12 19:21:31 (IP: 192.168.1.34)";
$PMBP_SYS_VAR['dir_lists']="1";
$PMBP_SYS_VAR['memory_limit']="38000000";
$PMBP_SYS_VAR['except_tables']="";
$PMBP_SYS_VAR['scheduled_debug']="0";
$PMBP_SYS_VAR['schedule_all_dbs']="0";
$PMBP_SYS_VAR['ftp_timeout']="10";
$PMBP_SYS_VAR['dir_email_backup']="0";
$PMBP_SYS_VAR['F_dbs']="sar|sarmicro";
$PMBP_SYS_VAR['F_comment']="";
$PMBP_SYS_VAR['F_tables']="on";
$PMBP_SYS_VAR['F_data']="on";
$PMBP_SYS_VAR['F_drop']="on";
$PMBP_SYS_VAR['F_compression']="";
$PMBP_SYS_VAR['F_ftp_dirs']="";
$PMBP_SYS_VAR['F_ftp_dirs_2']="";
$PMBP_SYS_VAR['F_packed']="";
$PMBP_SYS_VAR['F_updates']="1";
$PMBP_SYS_VAR['F_ffadd']="1";
$PMBP_SYS_VAR['EXS_scheduled_file']="???.php";
$PMBP_SYS_VAR['EXS_scheduled_dir']="/var/www/html/sar/login/";
$PMBP_SYS_VAR['EXS_period']="/24";
$PMBP_SYS_VAR['C_disable_config']="0";
$PMBP_SYS_VAR['C_disable_sqlquery']="0";
$PMBP_SYS_VAR['security_key']="b0adeb28351329cae27acc0c9d48636f";

?>